image: ubuntu

install:
  - java -version

build_script:
  - ant -buildfile ./src/build/build.xml

artifacts:
  - path: 'build/jars/ZCashSwingWalletUI*.jar'
    name: JARs

  - path: '*.deb'
    name: Debian package
