image: ubuntu

environment:
  PACKAGECLOUD_TOKEN:
    secure: xx7HMgFYZZw9TVWrcdrPG0a4t+M7KGBs/A9ayG7UJjjuM61HyFNE7jjXhvSlqeoFNFYII3wk8oYfB3T8OGgtvQ==

install:
  - java -version

configuration: debug

build_script:
  - ant -buildfile ./src/build/build.xml
  - mvn -P installer clean package

artifacts:
  - path: 'build/jars/ZCashSwingWalletUI*.jar'
    name: JARs

  - path: 'build/ubuntu-package/*.deb'
    name: Debian package

  - path: 'installer/target/zcash-wallet-installer.exe'
    name: Windows installer

for:
-
  branches:
    only:
      - master

  deploy_script:
    - gem install package_cloud
    - package_cloud push blbradley/zcash-wallet-dev/ubuntu/xenial build/ubuntu-package/*.deb
