image: ubuntu

environment:
  PACKAGECLOUD_TOKEN:
    secure: xx7HMgFYZZw9TVWrcdrPG0a4t+M7KGBs/A9ayG7UJjjuM61HyFNE7jjXhvSlqeoFNFYII3wk8oYfB3T8OGgtvQ==
  GITHUB_TOKEN:
    secure: 41ct1Jt+6D2+w8kuO4M3MqYo/opOczBAbsr7OxV3HZZyS/S+9rUsUbeyTWg14jXj
  VERSION: 0.84.0

install:
  - java -version

configuration:
  - debug
  - release

build_script:
  - ant -buildfile ./src/build/build.xml $CONFIGURATION
  - mvn -P installer clean package
  - bash ./build-mac.sh

artifacts:
  - path: 'build/jars/ZCashSwingWalletUI*.jar'
    name: JARs

  - path: 'build/ubuntu-package/*.deb'
    name: Debian package

  - path: 'installer/target/zcash-wallet-installer.exe'
    name: Windows installer

  - path: 'build/mac'
    name: ZcashSwingWalletMac

deploy:
  - provider: GitHub
    tag: v${VERSION}
    release: Zcash Desktop GUI Wallet ${VERSION}
    artifact: build/ZcashSwingWalletMac.zip
    auth_token: $GITHUB_TOKEN
    on:
      branch: master
      configuration: release
  - provider: GitHub
    tag: v${VERSION}
    release: Zcash Desktop GUI Wallet ${VERSION}
    artifact: installer/target/zcash-wallet-installer.exe
    auth_token: $GITHUB_TOKEN
    on:
      branch: master
      configuration: release
  - provider: GitHub
    tag: v${VERSION}
    release: Zcash Desktop GUI Wallet ${VERSION}
    artifact: /build\/ubuntu-package\/.*\.deb/
    auth_token: $GITHUB_TOKEN
    on:
      branch: master
      configuration: release

for:
-
  branches:
    only:
      - develop

  deploy_script:
    - gem install package_cloud
    - package_cloud push blbradley/zcash-wallet-dev/ubuntu/xenial build/ubuntu-package/*.deb
