image: ubuntu

environment:
  PACKAGECLOUD_TOKEN:
    secure: xx7HMgFYZZw9TVWrcdrPG0a4t+M7KGBs/A9ayG7UJjjuM61HyFNE7jjXhvSlqeoFNFYII3wk8oYfB3T8OGgtvQ==
  GITHUB_TOKEN:
    secure: 41ct1Jt+6D2+w8kuO4M3MqYo/opOczBAbsr7OxV3HZZyS/S+9rUsUbeyTWg14jXj


install:
  - java -version

configuration: debug

build_script:
  - ant -buildfile ./src/build/build.xml
  - mvn -P installer clean package
  - bash ./build-mac.sh

artifacts:
  - path: 'build/jars/ZCashSwingWalletUI*.jar'
    name: JARs

  - path: 'build/ubuntu-package/*.deb'
    name: Debian package

  - path: 'installer/target/zcash-wallet-installer.exe'
    name: Windows installer

  - path: 'build/mac'
    name: ZcashSwingWalletMac

for:
-
  branches:
    only:
      - release-0.84

  deploy:
    - provider: GitHub
      artifact: build/mac/ZcashSwingWalletMac.zip
      token: $GITHUB_TOKEN

  deploy_script:
    - gem install package_cloud
    - package_cloud push blbradley/zcash-wallet-dev/ubuntu/xenial build/ubuntu-package/*.deb
